// Every icon the game draws, grouped by where it sits, for icon-lab.html.
//
// Written 23 Sep 2026 from a sweep of lobby-build (the image files, what uses them, and the
// icons drawn in code), checked against the files. ICON-COLOURS.md in the wocg repo has the
// sources, the file:line of every use and the findings.
//
// A state names its art one of four ways:
//   file:   a file in static/images (or static/pieces). An SVG is drawn as it ships. A PNG is
//           drawn from its Sketch vector in sketch/ (`vector:` names another one), which matches
//           the PNG pixel for pixel (`node icon-lab-parts/check.js --png`).
//   sketch: a vector exported from the Sketch file that the site does not ship.
//   inline: an icon the site draws in code, written out with its colours in inline/.
// `ground` on a state draws that state on its own ground. `flip` mirrors it, as the site does.
// An icon's `grounds` are the papers it sits on; `stage` is the one its big view stands on.
// `flag`: 'both' or 'on' draws with the redesign on; 'off' only with it off; 'never' not at all.
// `size` is the size the site draws the icon at with the redesign on, on a desktop that is not compact
// (the sweep's sizes, checked 23 Sep 2026). Where the site draws it at no fixed size, `siteSize` is the
// size it takes in the usual case and `sizeNote` says why.
const S = (key, label, file, extra) => Object.assign({ key, label, file }, extra || {});
const I = (key, label, inline, extra) => Object.assign({ key, label, inline }, extra || {});
const K = (key, label, sketch, extra) => Object.assign({ key, label, sketch }, extra || {});
const L = (key, label, file, extra) => Object.assign({ key, label, file }, extra || {});

module.exports = {
  grounds: {
    page: { name: 'Page paper', color: '#F9F6F2' },
    band: { name: 'Band paper', color: '#F4EEE5' },
    white: { name: 'A white card', color: '#FFFFFF' },
    tray: { name: 'The games bar', color: '#E4DDD0' },
    green: { name: 'The green thumb', color: '#43A038' },
    plateBlue: { name: 'The blue plate', color: '#ABD2FF' },
    plateRed: { name: 'The red plate', color: '#FCBCB4' },
    tileFelt: { name: 'A table tile', css: "#327333 url('static/pieces/wallpaper/fabrics/green-felt.jpg') 0 0/100px 100px repeat", mean: '#1E5B1C' },
    scrim: { name: 'Behind a dialog', css: 'linear-gradient(rgba(0,0,0,.48),rgba(0,0,0,.48)), #F9F6F2', mean: '#81807E' },
    scrimOld: { name: 'The old scrim', css: 'linear-gradient(rgba(0,0,0,.64),rgba(0,0,0,.64)), #F9F6F2', mean: '#5A5957' },
    oldPage: { name: 'The old grey', color: '#F8F9FA' },
    oldPill: { name: 'The old yellow pill', color: '#FFE066' },
  },
  // The overview at the top of the page: each icon in its default state, side by side, one row per version.
  // [icon id, state key, the name under it]
  overview: [
    { id: 'ovTable', title: 'At the table and in the menubar', ground: 'band',
      icons: [['menuActivity', 'rest', 'Bell'], ['menuFriends', 'rest', 'Friends'], ['tableMenu', 'rest', 'Table'], ['chatMenu', 'rest', 'Chat'],
        ['hintMenu', 'rest', 'Hint'], ['playMenu', 'rest', 'Play'], ['crown', 'rest', 'Subscriber'], ['playerLiked', 'rest', 'Liked'],
        ['playerLeaving', 'rest', 'Leave'], ['playerMore', 'rest', 'More'], ['sortArrows', 'left', 'Sort']] },
    { id: 'ovFriends', title: 'In the friends panel', ground: 'white',
      icons: [['friendMessage', 'rest', 'Message'], ['friendInvite', 'rest', 'Invite'], ['send', 'rest', 'Send'],
        ['friendSearch', 'rest', 'Search'], ['friendSearchClose', 'rest', 'Close search'], ['friendBack', 'rest', 'Back']] },
    { id: 'ovTiles', title: 'On the table tiles and plates', ground: 'tileFelt',
      icons: [['likedBadge', 'rest', 'Liked'], ['botBadge', 'rest', 'Bot'], ['highReputationBadge', 'rest', 'Finishes all'],
        ['cleanMeldBadge', 'rest', 'Finishes most'], ['dealer', 'rest', 'Dealer']] },
  ],
  // The felt switch in the lab's bar. The average colours were measured from the files.
  wallpapers: [
    { id: 'green-felt.jpg', name: 'Green felt', url: 'static/pieces/wallpaper/fabrics/green-felt.jpg', size: 100, mean: '#1E5B1C' },
    { id: 'charcoal-felt-1.jpg', name: 'Charcoal felt', url: 'static/pieces/wallpaper/fabrics/charcoal-felt-1.jpg', size: 100, mean: '#2C2B33' },
    { id: 'denim-weave.jpg', name: 'Denim weave', url: 'static/pieces/wallpaper/fabrics/denim-weave.jpg', size: 448, mean: '#243847' },
    { id: 'rose-weave.jpg', name: 'Rose weave', url: 'static/pieces/wallpaper/fabrics/rose-weave.jpg', size: 384, mean: '#9B533D' },
    { id: 'moss-print-4.jpg', name: 'Moss print', url: 'static/pieces/wallpaper/assorted/moss-print-4.jpg', size: 512, mean: '#79AD5A' },
    { id: 'pewter-felt.jpg', name: 'Pewter felt', url: 'static/pieces/wallpaper/fabrics/pewter-felt.jpg', size: 100, mean: '#909090' },
    { id: 'sky-linen.jpg', name: 'Sky linen', url: 'static/pieces/wallpaper/fabrics/sky-linen.jpg', size: 512, mean: '#D9E6EE' },
  ],
  categories: [
    { id: 'menubar', title: 'The menubar',
      desc: 'The bar at the top of every page away from a table. At a table the bell and the friends icon sit in the pill in the felt’s top right corner, on the same band paper.',
      icons: [
        { id: 'menuActivity', name: 'The bell', size: [40, 32], grounds: ['band'], flag: 'both',
          states: [S('rest', 'Rest', 'menuActivity.svg'), S('hover', 'Hover or open', 'menuActivityHover.svg'),
            S('note', 'Something new', 'menuActivityNotification.svg', { keep: ['#F03E3E', '#C92A2A'] }), S('noteHover', 'Something new, open', 'menuActivityNotificationHover.svg', { keep: ['#F03E3E', '#C92A2A'] })],
          lottie: [L('ring', 'It rings when something new arrives', 'menuActivityNotification.json', { state: 'note' }),
            L('first', 'The first new thing arrives', 'menuActivityNotificationTransition.json', { state: 'note' })],
          where: ['In the menubar, left of your avatar.', 'In the pill in the felt’s top right corner at a table.'],
          note: 'The rings play only when animations are set to all.' },
        { id: 'menuFriends', name: 'Friends', size: [40, 32], grounds: ['band'], flag: 'both',
          states: [S('rest', 'Rest', 'menuFriends.svg'), S('hover', 'Hover or open', 'menuFriendsHover.svg'),
            S('count', 'Friends online', 'menuFriendsCount.svg'), S('countHover', 'Friends online, open', 'menuFriendsCountHover.svg'),
            S('note', 'Unread message', 'menuFriendsNotification.svg', { keep: ['#F03E3E', '#C92A2A'] }), S('noteHover', 'Unread message, open', 'menuFriendsNotificationHover.svg', { keep: ['#F03E3E', '#C92A2A'] })],
          lottie: [L('ring', 'It rings when a message arrives', 'menuFriendsNotification.json', { state: 'note' }),
            L('first', 'The first message arrives', 'menuFriendsNotificationTransition.json', { state: 'note' })],
          where: ['In the menubar, left of your avatar.', 'In the pill in the felt’s top right corner at a table.'] },
        { id: 'caret', name: 'The caret', size: [8, 7], flag: 'both', grounds: ['band', 'tray', 'green'],
          states: [I('menubar', 'After Games in the menubar', 'caret.svg', { ground: 'band' }),
            I('tray', 'On the games bar’s More', 'caret--tray.svg', { ground: 'tray' }),
            I('picked', 'More holds the pick', 'caret--picked.svg', { ground: 'green' })],
          where: ['After Games in the menubar, on the games bar’s More, on a catalog tile’s Play button, on the stats picker and on the daily deal’s month arrows.'],
          note: 'The caret is a mask, so it takes the colour of the words beside it. It is the arrowDown file. On the green thumb it is white with no outline, where every other white on a green has one (Law 5).' },
      ] },

    { id: 'friends', title: 'The friends panel',
      desc: 'The panel the friends icon opens, in the menubar and at a table. With the redesign on, its buttons still wear the old kit: cold greys, the old light blue and lime, and round corners. Each button is drawn with its fill and ring, so they recolour together.',
      icons: [
        { id: 'friendMessage', name: 'Message a friend', size: [24, 24], grounds: ['white'], flag: 'both',
          states: [I('rest', 'Rest', 'message.svg'), I('hover', 'Hover', 'message--hover.svg'), I('unread', 'Unread messages', 'message--unread.svg', { size: [31, 31], keep: ['#F03E3E', '#C92A2A'] })],
          where: ['On every row of the friends list, and on a liked player’s row.'],
          note: 'This is the icon the Sketch file calls friendsListChat. The site draws it in code, with CSS colours.' },
        { id: 'friendInvite', name: 'Invite to your table', size: [24, 24], grounds: ['white'], flag: 'both',
          states: [I('rest', 'Rest', 'invite.svg'), I('hover', 'Hover', 'invite--hover.svg'), I('sent', 'Invite sent', 'invite--sent.svg')],
          where: ['On a friend’s row, when you sit at a table with a free seat and the friend is online.'] },
        { id: 'friendSearch', name: 'Search', size: [24, 24], grounds: ['page'], flag: 'both',
          states: [I('rest', 'Rest', 'friendsSearch.svg'), I('hover', 'Hover', 'friendsSearch--hover.svg')],
          where: ['In the panel’s head. It opens the search field.'] },
        { id: 'friendSearchClose', name: 'Close the search', size: [24, 24], grounds: ['page'], flag: 'both',
          states: [I('rest', 'Rest', 'friendsSearchClose.svg'), I('hover', 'Hover', 'friendsSearchClose--hover.svg')],
          where: ['In the panel’s head while you search.'] },
        { id: 'friendBack', name: 'Back to the list', size: [24, 24], grounds: ['oldPage'], flag: 'both',
          states: [I('rest', 'Rest', 'conversationBack.svg'), I('hover', 'Hover', 'conversationBack--hover.svg')],
          where: ['In a conversation’s head. The head keeps the old grey paper with the redesign on.'],
          note: 'A mask of the sort arrow (sortArrowLeft), filled with the old cold greys.' },
        { id: 'send', name: 'Send', size: [32, 32], grounds: ['oldPage', 'white'], flag: 'both',
          states: [I('rest', 'Rest', 'send.svg'), I('hover', 'Hover', 'send--hover.svg'), I('off', 'Nothing typed yet', 'send--off.svg')],
          where: ['In a conversation with a friend, on the old grey.', 'In the chat panel at a table, on white.'] },
      ] },

    { id: 'tablechrome', title: 'The table’s pills and seat buttons',
      desc: 'At a table, a pill stands in each of the felt’s top corners and two square buttons sit at your own name plate. All of them are band paper on the felt. The same art drew the old table bar at the bottom of the felt, so a few hover states show only on the old look.',
      icons: [
        { id: 'tableMenu', name: 'Table (the round i)', size: [20, 20], grounds: ['band'], flag: 'both',
          states: [S('rest', 'Rest', 'tableMenu.png'), S('active', 'Panel open', 'tableMenuActive.png'), S('hover', 'Hover, old look only', 'tableMenuHover.png', { real: false })],
          where: ['The middle cell of the pill in the felt’s top left corner. It opens the Table panel.', 'Redrawn at 16px in the tray’s colours, it is also the info icon after a setting on a phone (Dialogs and settings).'] },
        { id: 'playMenu', name: 'Play (the fanned cards)', size: [25, 20], grounds: ['band'], flag: 'both',
          states: [S('rest', 'Rest', 'playMenu.svg'), S('hover', 'Hover, old look only', 'playMenuHover.svg', { real: false })],
          where: ['The third cell of the pill in the felt’s top left corner, at 25 by 20. It opens the games list.', 'It also stands in for New game on a solo table’s second seat button.'] },
        { id: 'hintMenu', name: 'Hint (the bulb)', size: [24, 24], grounds: ['band'], flag: 'both',
          states: [S('rest', 'Rest', 'hintMenu.png'), S('hover', 'Hover', 'hintMenuHover.png')],
          where: ['The square button at the left end of your own name plate.'] },
        { id: 'chatMenu', name: 'Chat (the speech bubble)', size: [24, 24], grounds: ['band'], flag: 'both',
          states: [S('rest', 'Rest', 'chatMenu.png'), S('hover', 'Hover', 'chatMenuHover.png'), S('active', 'Chat open', 'chatMenuActive.png')],
          where: ['The square button at the right end of your own name plate.'] },
      ] },

    { id: 'plates', title: 'Beside the name plates',
      desc: 'Small tabs stand up behind a name plate, on band paper with the felt line. The dealer chip sits on a plate’s corner, half on the plate and half on the felt, and the turn timer stands beside the plate.',
      icons: [
        { id: 'crown', name: 'A subscriber (the crown)', size: [24, 24], grounds: ['band'], flag: 'both',
          states: [S('rest', 'Rest', 'crown.svg')], where: ['A tab behind a subscriber’s name plate.'] },
        { id: 'playerLiked', name: 'A player you liked (the star)', size: [24, 24], grounds: ['band'], flag: 'both',
          states: [S('rest', 'Rest', 'playerLiked.svg')], where: ['A tab behind the plate of a player you liked.'] },
        { id: 'playerMore', name: 'Like, block or mute (the dots)', size: [24, 24], grounds: ['band'], flag: 'both',
          states: [S('rest', 'Rest', 'playerMore.svg')], where: ['A tab behind every other player’s plate. It opens the player’s menu.'] },
        { id: 'playerLeaving', name: 'Leaving (the door)', size: [24, 24], grounds: ['band'], flag: 'both',
          states: [S('rest', 'On a tab', 'playerLeaving.svg'), S('pill', 'In the pill, mirrored', 'playerLeaving.svg', { flip: true, real: false })],
          where: ['A tab behind a player who is leaving.', 'Mirrored, the first cell of the pill in the felt’s top left corner: Leave.'] },
        { id: 'sortArrows', name: 'Sort your hand', size: [24, 24], grounds: ['band'], flag: 'both',
          states: [S('left', 'Left', 'sortArrowLeft.svg'), S('right', 'Right', 'sortArrowRight.svg')],
          where: ['A tab behind your own plate in Gin Rummy, Rummy, Crazy Eights and Bridge.'] },
        { id: 'dealer', name: 'The dealer chip', size: [32, 32], grounds: ['plateBlue', 'plateRed', 'felt'], stage: 'felt', flag: 'both',
          states: [S('rest', 'Full size', 'dealer.svg'), S('small', 'On a small table', 'dealerSmall.svg', { size: [24, 24] })],
          where: ['On the dealer’s name plate, over its top corner.'] },
        { id: 'turnTimer', name: 'The turn timer', size: [52, 52], grounds: ['felt'], flag: 'both',
          states: [I('rest', 'Counting down', 'turnTimer.svg'), I('red', 'The last five seconds', 'turnTimer--red.svg')],
          where: ['Beside the plate of the player whose turn it is.'],
          note: 'Drawn in code: a 32px disc with the felt line outside, a 4px ring inside and the progress arc over it, with the 8px shadow round it (the drawing is 52px so the shadow fits). Redrawn 23 Sep 2026 from a live timer on dev at 1440 by 900, which it matches to within 2 of 255 inside the disc. Each edge is drawn once: the felt line is a disc under the rest, and the ring, the fill and the arc are one group cut at the disc’s edge, so no light hairline shows where the arc meets the line. The site paints the number and the arc in one colour; the new colours give the arc its own. It counts from 10 and turns red at 5. Its yellow is not the button’s yellow: the colour document lists it as open (7.3, item 19).' },
      ] },

    { id: 'badges', title: 'Badges on the table tiles',
      desc: 'The table tiles on the frontpage, in Find tables and in the table preview show who sits where. A badge sits on the corner of a seated player’s name plate, half on the plate and half on the felt.',
      icons: [
        { id: 'likedBadge', name: 'A player you liked', size: [16, 16], grounds: ['plateBlue', 'plateRed', 'tileFelt'], stage: 'tileFelt', flag: 'both',
          states: [S('rest', 'Rest', 'likedBadge.svg')], where: ['On the plate of a player you liked.'] },
        { id: 'botBadge', name: 'A bot in the seat', size: [16, 16], grounds: ['plateBlue', 'plateRed', 'tileFelt'], stage: 'tileFelt', flag: 'both',
          states: [S('rest', 'Rest', 'botBadge.svg')], where: ['On a bot’s plate. Three bots also sit in the frontpage’s “You never wait” picture.'] },
        { id: 'highReputationBadge', name: 'Finishes every game', size: [20, 20], grounds: ['plateBlue', 'plateRed', 'tileFelt'], stage: 'tileFelt', flag: 'both',
          states: [S('rest', 'Rest', 'highReputationBadge.svg')], where: ['On the plate of a player who finishes all their games.'] },
        { id: 'cleanMeldBadge', name: 'Finishes most games', size: [20, 20], grounds: ['plateBlue', 'plateRed', 'tileFelt'], stage: 'tileFelt', flag: 'both',
          states: [S('rest', 'Rest', 'cleanMeldBadge.svg')], where: ['On the plate of a player who finishes 70 to 99 percent of their games. The share is written on it.'],
          note: 'Its number is written in the green button’s ring, and its art is still lime: the colour document lists it as open (7.3, item 17).' },
      ] },

    { id: 'tiles', title: 'The table tiles’ marks',
      desc: 'The felt tiles on the frontpage and in the table preview carry their facts as small white marks, drawn in code. Find tables lists a table’s options with a tick.',
      icons: [
        { id: 'tableClock', name: 'The table’s clock', size: [10, 10], grounds: ['tileFelt'], flag: 'on',
          states: [I('open', 'Not started', 'tableClock--open.svg'), I('play', 'In play', 'tableClock.svg'), I('full', 'Full', 'tableClock--full.svg')],
          where: ['Bottom left of a tile, before “0 min”, “12 min” or the live score.'] },
        { id: 'markRanked', name: 'Ranked (the crown)', size: [18, 18], grounds: ['tileFelt'], flag: 'on',
          states: [I('rest', 'Rest', 'markRanked.svg')], where: ['Bottom right corner of a ranked table’s tile.'] },
        { id: 'markPrivate', name: 'Private (the lock)', size: [18, 18], grounds: ['tileFelt'], flag: 'on',
          states: [I('rest', 'Rest', 'markPrivate.svg')], where: ['Bottom right corner of a private table’s tile.'],
          note: 'Its keyhole is the felt’s own green, written into the art.' },
        { id: 'markLimited', name: 'Limited (a person)', size: [18, 18], grounds: ['tileFelt'], flag: 'on',
          states: [I('rest', 'Rest', 'markLimited.svg')], where: ['Registered only, experienced only or no bots. The tip says which.'] },
        { id: 'markHouseRule', name: 'A house rule (the asterisk)', size: [18, 18], grounds: ['tileFelt'], flag: 'on',
          states: [I('rest', 'Rest', 'markHouseRule.svg')], where: ['The table plays one of the game’s optional rules. The tip names it.'] },
        { id: 'hostPlus', name: 'New table (the plus)', size: [11, 11], grounds: ['tileFelt'], flag: 'on',
          states: [I('rest', 'Rest', 'hostPlus.svg')], where: ['Before “New table” on the frontpage’s host tile.'] },
        { id: 'inviteEnvelope', name: 'You’re invited (the envelope)', size: [12, 12], grounds: ['tileFelt'], flag: 'on',
          states: [I('rest', 'Rest', 'inviteEnvelope.svg')], where: ['Before “You’re invited” on a tile you were invited to.'] },
        { id: 'checkmark', name: 'An option on or off (the tick)', size: [24, 24], grounds: ['white'], flag: 'both',
          states: [S('on', 'On', 'checkmark.png'), S('off', 'Off', 'checkmarkDisabled.png')],
          where: ['Before each table option in a Find tables listing, such as “Experienced only”.'] },
      ] },

    { id: 'felt', title: 'On the felt',
      desc: 'Pieces drawn straight on the cloth. The felt behind them is the wallpaper the player picked, from near black to near white, so try the felt switch in the bar at the top.',
      icons: [
        { id: 'hintArrow', name: 'The hint arrow', size: [24, 40], grounds: ['felt'], flag: 'both', realStates: 1,
          states: [S('down', 'Down', 'hintArrowDown.svg'), S('up', 'Up', 'hintArrowUp.svg'), S('left', 'Left', 'hintArrowLeft.svg', { size: [40, 24] }), S('right', 'Right', 'hintArrowRight.svg', { size: [40, 24] })],
          where: ['Blinks beside the card or the button the hint suggests.'] },
        { id: 'suits', name: 'Suit confetti', size: [40, 40], sizeNote: '16 to 40px as they fly', grounds: ['felt'], flag: 'both',
          states: [S('heart', 'Heart', 'suitHeart.svg'), S('diamond', 'Diamond', 'suitDiamond.svg'), S('club', 'Club', 'suitClub.svg'), S('spade', 'Spade', 'suitSpade.svg')],
          where: ['Bursts from a played card in Hearts and Spades, and rises from the trump tab when trump is picked. Only with animations set to all.'] },
        { id: 'canastaStar', name: 'A complete canasta', size: [26, 18], grounds: ['felt'], flag: 'both',
          states: [I('natural', 'Natural', 'canastaStar.svg'), I('mixed', 'Mixed', 'canastaStar--mixed.svg')],
          where: ['In the small badge under a meld once it is a canasta, in place of its card count.'],
          note: 'The badge is the meld’s count tab (pieces.scss 1925 to 1965): green for a natural canasta, yellow for a mixed one, edged in the cards’ #252525. Its tab keeps two round corners.' },
        { id: 'cribbageBoard', name: 'The cribbage board', size: [72, 234], grounds: ['felt'], flag: 'both',
          states: [S('rest', 'Rest', 'cribbageBoard.svg')], where: ['Stands on the right side of the cribbage table.'],
          note: 'Drawn here at 45% of its file size. Its tracks already wear the plate blue and the plate red.' },
        { id: 'cribbagePins', name: 'The cribbage pegs', size: [12, 18], siteSize: [5.4, 8.1], sizeNote: 'on a 72px board', grounds: ['felt'], flag: 'both',
          states: [S('blueInk', 'Blue, redesign', 'cribbagePinBlueInk.svg'), S('redInk', 'Red, redesign', 'cribbagePinRedInk.svg'),
            S('blue', 'Blue, old look', 'cribbagePinBlue.svg', { real: false }), S('red', 'Red, old look', 'cribbagePinRed.svg', { real: false })],
          where: ['Two per colour, in the holes of the board.'],
          note: 'With the redesign on the pegs wear the plate inks, so a peg reads as its plate. Another session made that change on 23 Sep 2026 and it is not committed yet (pieces.scss 1720 to 1730).' },
      ] },

    { id: 'gameover', title: 'Game over and hand over',
      desc: 'The panel at the end of a game or a hand, on the page paper over the dimmed felt. Its headers are animations, drawn here from their Sketch stills and played from the site’s own files. Click an animation to play it.',
      icons: [
        { id: 'gameOverHeader', name: 'Game over (the cup)', size: [296, 112], grounds: ['page'], wide: true, flag: 'both',
          states: [K('still', 'Still, from Sketch', 'gameOverHeader.svg')],
          lottie: [L('play', 'Plays when the game ends', 'gameOverHeader.json', { holdEnd: true, size: [320, 140] })],
          where: ['At the top of the game over panel, behind “X wins!”.'],
          note: 'In a team game with the redesign on, the table repaints the green ribbon in the winning team’s plate: #ABD2FF edged #75A4D2, or #FCBCB4 edged #D4837E (Table.js).' },
        { id: 'handOverHeader', name: 'Hand over', size: [268, 98], grounds: ['page'], wide: true, flag: 'both',
          states: [K('still', 'Still, from Sketch', 'handOverHeader.svg')],
          lottie: [L('play', 'Plays when the hand ends', 'handOverHeader.json', { holdEnd: true, size: [320, 140] })],
          where: ['At the top of the hand over panel, behind “Hand 3 over!”.'] },
        { id: 'medals', name: 'Place medals', size: [56, 48], grounds: ['page'], flag: 'both',
          states: [K('first', 'First', '1.svg'), K('second', 'Second', '2.svg'), K('third', 'Third', '3.svg'), K('fourth', 'Fourth to sixth', '4.svg')],
          lottie: [L('first', 'First, as it plays', '../pieces/medal/classic/1.json', { state: 'first', holdEnd: true, size: [56, 56] })],
          where: ['On each row of the game over panel, by the player’s place.'],
          note: 'The site plays them from static/pieces/medal/classic/1 to 6.json. The stills are the Sketch rosettes, in the same colours.' },
        { id: 'handOverBackground', name: 'The rays behind the panel', size: [160, 160], sizeNote: 'fills the window', grounds: ['felt'], stage: 'felt', flag: 'both',
          states: [S('rest', 'Its colours', 'handOverBackground.svg'), S('drawn', 'As the site draws it', 'handOverBackground.svg', { css: 'opacity:.16;filter:blur(6px)', real: false })],
          where: ['Spins slowly behind the game over and hand over panels.'],
          note: 'With the redesign on it is drawn at 16% with a 6px blur, so its colour barely shows.' },
        { id: 'shootTheMoon', name: 'Shoot the moon (Hearts)', size: [296, 118], grounds: ['band'], flag: 'both',
          states: [S('rest', 'Rest', 'shootTheMoon.svg')], where: ['The celebration banner when a player shoots the moon.'] },
        { id: 'shootTheSun', name: 'Shoot the sun (Hearts)', size: [296, 118], grounds: ['band'], flag: 'both',
          states: [S('rest', 'Rest', 'shootTheSun.svg')], where: ['The celebration banner when a player shoots the sun.'] },
        { id: 'slam', name: 'A slam (Bridge)', size: [296, 112], grounds: ['band'], flag: 'both',
          states: [S('rest', 'Rest', 'slam.svg')], where: ['Bridge’s banner for a slam or a rubber.'] },
        { id: 'ratingStarsGameOver', name: 'Rate the game, in the panel', size: [32, 32], grounds: ['white'], flag: 'both',
          states: [I('full', 'Picked', 'ratingStarGameOver.svg'), I('empty', 'Not picked', 'ratingStarGameOver--empty.svg')],
          where: ['The five stars of the “Rate this game” prompt in the game over panel.'],
          note: 'The game page’s own stars took the scheme’s colours. These still wear the old ones.' },
      ] },

    { id: 'dialogs', title: 'Dialogs and settings',
      desc: 'The redesigned dialogs and the settings, drawn in code, and the two old boxes that still open on the old scrim.',
      icons: [
        { id: 'closeCross', name: 'Close a dialog', size: [20, 20], grounds: ['scrim'], flag: 'both',
          states: [I('rest', 'Rest', 'closeCross.svg')], where: ['Outside the top right corner of every dialog, on the dimmed page.'] },
        { id: 'closeModal', name: 'Close, on the old boxes', size: [32, 32], grounds: ['scrimOld'], flag: 'both',
          states: [S('rest', 'Rest', 'closeModal.svg')], where: ['Beside the Find tables box and the Help and rules box. Both still sit on the old, darker scrim.'] },
        { id: 'infoI', name: 'What a setting means (the round i)', size: [16, 16], grounds: ['white'], flag: 'both',
          states: [I('rest', 'Rest', 'infoI.svg'), I('hover', 'Hover', 'infoI--hover.svg'), I('open', 'Open', 'infoI--open.svg')],
          where: ['After a setting’s title on a phone. A tap opens its explanation.'],
          note: 'The table icon’s art, redrawn in the tray’s colours.' },
        { id: 'pickMark', name: 'Yours (the pick mark)', size: [20, 20], grounds: ['band'], flag: 'both',
          states: [I('rest', 'Rest', 'pickMark.svg')], where: ['In the corner of the picked tile in Settings, Design: your avatar, wallpaper, cards and back.'],
          note: 'A squircle at half its side (_wm-settings.scss 363 to 372), drawn so here.' },
        { id: 'seatCheck', name: 'A seat count box', size: [24, 24], grounds: ['white'], flag: 'both',
          states: [I('on', 'Picked', 'seatCheck.svg'), I('off', 'Not picked', 'seatCheck--off.svg')],
          where: ['The 2, 3 and 4 player boxes in the table options.'],
          note: 'A 12px squircle, half its side (_wm-dialogs.scss 164 to 172), drawn so here.' },
        { id: 'rowChevron', name: 'Opens a list (the chevron)', size: [8, 12], grounds: ['white'], flag: 'both',
          states: [I('rest', 'Rest', 'rowChevron.svg')], where: ['At the end of a settings row that opens something, such as your blocked players.'] },
        { id: 'glyphCheck', name: 'Done (the tick in a message)', size: [16, 16], grounds: ['page', 'white'], flag: 'both',
          states: [I('auth', 'Sign in and sign up', 'glyphCheck.svg', { ground: 'page' }), I('settings', 'Settings forms', 'glyphCheck--settings.svg', { ground: 'white' })],
          where: ['Before a success message: BoxForm.js 200 to 207 writes “✔ ” before the words, in the sign in and sign up boxes and the settings forms.'],
          note: 'A letter, not a drawing, so its shape is whatever font the system finds for ✔, and it is two greens: the auth box writes in --btn-green (_wm-auth.scss 183), the settings forms keep the old #4F800B.' },
      ] },

    { id: 'daily', title: 'The daily deal and the leaderboards',
      desc: 'The daily deal card and dialog, the leaderboard card on the frontpage, the rating stars on a game page and the leaderboard pages.',
      icons: [
        { id: 'dailyChallenge', name: 'The daily challenge trophies', size: [34, 32], grounds: ['band'], flag: 'on',
          states: [S('gold', 'Gold', 'dailyChallengeGoldSmall.svg'), S('silver', 'Silver', 'dailyChallengeSilverSmall.svg'), S('bronze', 'Bronze', 'dailyChallengeBronzeSmall.svg', { size: [33, 32] })],
          where: ['At the thresholds of the award strip in the daily deal card and dialog.'],
          note: 'The medal colours are Open Color stops and the silver is cold: the colour document lists it as open (7.3, item 18).' },
        { id: 'dealDayCheck', name: 'A won day', size: [32, 32], grounds: ['white'], flag: 'on',
          states: [S('rest', 'Rest', 'dealDayCheck.svg')], where: ['In place of the day’s number in the daily deal calendar, on a day you won.'],
          note: 'A mask filled with the green button’s green.' },
        { id: 'dealDayPlay', name: 'Play this day (a leftover)', size: [14, 16], grounds: ['band'], flag: 'on',
          states: [I('rest', 'Hover', 'dealDayPlay.svg')], where: ['Over a hovered day in the daily deal dialog.'],
          note: 'A leftover from the old look: an old rule outranks the redesign’s reset, so this yellow triangle still covers the day’s number, and on a won day it covers the green check (GameSelectors.scss 405 to 433).' },
        { id: 'moveChips', name: 'Moving up or down', size: [16, 14], grounds: ['white', 'band'], flag: 'on',
          states: [I('up', 'Up', 'moveUp.svg'), I('down', 'Down', 'moveDown.svg')],
          where: ['After a player’s rank on the frontpage leaderboard card and on the leaderboard pages.'],
          note: 'The chips wear the light green and the plate red with their inks. The arrow is the caret. Their corner is an 8px squircle, held to half the chip’s height (_fp-cards.scss 182 to 205), drawn so here.' },
        { id: 'glyphHeart', name: 'A friend on the board (the heart)', size: [16, 16], grounds: ['white', 'band'], flag: 'on',
          states: [I('rest', 'Rest', 'glyphHeart.svg')], where: ['After a friend’s name on the frontpage leaderboard card.'],
          note: 'A letter (♥) in Open Color red 7 (LobbyWidgets.js 1724, _fp-cards.scss 168), so its shape is whatever font the system finds for it, and its red is on no rung: the colour document lists it as open (7.3, item 24).' },
        { id: 'ratingStars', name: 'Rate the game, on a game page', size: [32, 32], grounds: ['band'], flag: 'both',
          states: [I('full', 'Picked', 'ratingStar.svg'), I('empty', 'Not picked', 'ratingStar--empty.svg')],
          where: ['The five stars of the rating callout on each game page’s band.'] },
      ] },

    { id: 'footer', title: 'The footer',
      desc: 'The three social marks at the end of the footer’s legal row. They are masks in the label ink, and take the brand’s own colour under the pointer.',
      icons: [
        { id: 'socialX', name: 'X', size: [17, 17], grounds: ['band', 'page'], flag: 'on',
          states: [I('rest', 'Rest', 'socialX.svg'), I('hover', 'Hover, the brand', 'socialX--hover.svg')], where: ['The footer’s legal row.'] },
        { id: 'socialFacebook', name: 'Facebook', size: [19, 19], grounds: ['band', 'page'], flag: 'on',
          states: [I('rest', 'Rest', 'socialFacebook.svg'), I('hover', 'Hover, the brand', 'socialFacebook--hover.svg')], where: ['The footer’s legal row.'] },
        { id: 'socialYouTube', name: 'YouTube', size: [22, 22], grounds: ['band', 'page'], flag: 'on',
          states: [I('rest', 'Rest', 'socialYouTube.svg'), I('hover', 'Hover, the brand', 'socialYouTube--hover.svg')], where: ['The footer’s legal row.'] },
      ] },

    { id: 'old', title: 'The old look only', fold: true,
      desc: 'Drawn only with the redesign off: the classic table bar at the bottom of the felt, the round seat chips, the lobby’s yellow footer pills and the old footer. The redesign replaced all of these.',
      icons: [
        { id: 'pauseMenu', name: 'Pause', size: [20, 20], grounds: ['oldPage'], flag: 'off',
          states: [S('rest', 'Rest', 'pauseMenu.png'), S('hover', 'Hover', 'pauseMenuHover.png'), S('active', 'Paused', 'pauseMenuActive.png')],
          where: ['A cell of the classic table bar. The redesign has a Pause row in the Table panel instead.'] },
        { id: 'helpMenu', name: 'Help', size: [20, 20], grounds: ['oldPage'], flag: 'off',
          states: [S('rest', 'Rest', 'helpMenu.png'), S('hover', 'Hover', 'helpMenuHover.png')], where: ['A cell of the classic table bar.'] },
        { id: 'profileMenu', name: 'Profile', size: [20, 20], grounds: ['oldPage'], flag: 'off',
          states: [S('rest', 'Rest', 'profileMenu.png'), S('hover', 'Hover', 'profileMenuHover.png')], where: ['A cell of the classic table bar. It opens the settings.'] },
        { id: 'suitChip', name: 'The round seat chip', size: [24, 24], grounds: ['felt'], flag: 'off',
          states: [S('rest', 'Rest', 'suitChip.png')], where: ['The white disc under the trump suit and the seat glyphs. The redesign draws band paper tabs instead.'] },
        { id: 'lobbyPills', name: 'The lobby’s footer pills', size: [24, 24], grounds: ['oldPill'], flag: 'off',
          states: [S('tables', 'Tables', 'tableTables.svg'), S('help', 'Help', 'tableHelp.svg'), S('settings', 'Settings', 'tableSettings.svg')],
          where: ['The yellow pills of the old lobby’s footer bar, as icons in a narrow window.'] },
        { id: 'gameOverStar', name: 'Game over sparkles', size: [32, 32], grounds: ['felt'], flag: 'off',
          states: [S('rest', 'Rest', 'gameOverStar.svg')], where: ['Burst from the old game over panel’s cup, with animations set to all.'] },
        { id: 'arrowsOld', name: 'Moving up or down, old look', size: [13, 13], grounds: ['white'], flag: 'off',
          states: [S('up', 'Up', 'arrowPlus.png'), S('down', 'Down', 'arrowMinus.png')], where: ['Before a rank or rating change on the old leaderboard pages.'] },
        { id: 'socialXOld', name: 'X, old footer', size: [20, 20], grounds: ['oldPage'], flag: 'off',
          states: [I('rest', 'Rest', 'socialXOld.svg')], where: ['The old footer’s terms row.'] },
      ] },

    { id: 'unused', title: 'Shipped but never shown', fold: true,
      desc: 'Files in the site that nothing draws today: a rule points at a class no code sets, the element is hidden, or only a preload asks for the file.',
      icons: [
        { id: 'menuBurger', name: 'The menu (burger)', size: [32, 32], grounds: ['band'], flag: 'never', states: [S('rest', 'Rest', 'menuBurger.svg')], where: ['Only preloaded.'] },
        { id: 'menuClose', name: 'Close the menu', size: [32, 32], grounds: ['band'], flag: 'never', states: [S('rest', 'Rest', 'menuClose.svg')], where: ['The old footer bar’s toggle. Its image is hidden.'] },
        { id: 'ranksMenu', name: 'Ranks', size: [20, 20], grounds: ['oldPage'], flag: 'never',
          states: [S('rest', 'Rest', 'ranksMenu.png'), S('hover', 'Hover', 'ranksMenuHover.png')], where: ['Only preloaded. The classic table bar has no ranks cell.'] },
        { id: 'experiencedBadge', name: 'Experienced', size: [20, 20], grounds: ['plateBlue'], flag: 'never',
          states: [S('rest', 'Rest', 'experiencedBadge.png', { vector: '../inline/experiencedBadge.svg' })], where: ['No code sets its class since January.'],
          note: 'The PNG is the same art as the high reputation badge.' },
        { id: 'onlineBadge', name: 'Online', size: [20, 20], grounds: ['white'], flag: 'never', states: [S('rest', 'Rest', 'onlineBadge.svg')], where: ['No code sets its class since February.'] },
        { id: 'tableRules', name: 'Rules pill', size: [24, 24], grounds: ['oldPill'], flag: 'never', states: [S('rest', 'Rest', 'tableRules.svg')], where: ['The old footer bar hides this pill whenever it shows.'] },
        { id: 'tableLeaderboard', name: 'Leaderboard pill', size: [24, 24], grounds: ['oldPill'], flag: 'never', states: [S('rest', 'Rest', 'tableLeaderboard.svg')], where: ['The old footer bar hides this pill whenever it shows.'] },
        { id: 'menuQuestion', name: 'Help toggle', size: [24, 24], grounds: ['scrimOld'], flag: 'never',
          states: [S('rest', 'Rest', 'menuQuestion.png')], where: ['The old footer bar’s toggle. Its image is hidden.'] },
      ] },

    { id: 'sketch', title: 'In the Sketch file only', fold: true, sketchOnly: true,
      desc: 'Icons drawn on the Assets pages of WoCG-2.2.sketch that the site does not use. They are here so nothing drawn is missing.',
      icons: [
        { id: 'skTableSet', name: 'The table panel set', size: [24, 24], grounds: ['band'],
          states: [K('chat', 'Chat', 'tableChat.svg'), K('leave', 'Leave', 'tableLeave.svg'), K('pause', 'Pause', 'tablePause.svg'), K('resume', 'Resume', 'tableResume.svg'),
            K('invite', 'Invite', 'tableInvite.svg'), K('invited', 'Invited', 'tableInviteSuccess.svg'), K('next', 'Next lobby', 'tableNextLobby.svg'), K('send', 'Send', 'tableSend.svg'), K('info', 'Info', 'tableInfo.svg')] },
        { id: 'skFriends', name: 'The friends set', size: [24, 24], grounds: ['white'],
          states: [K('chat', 'friendsListChat', 'friendsListChat.svg'), K('search', 'Search', 'friendsSearch.svg'), K('close', 'Close', 'friendsClose.svg')],
          note: 'The site draws its own message, search and close buttons in code (The friends panel).' },
        { id: 'skRules', name: 'Rules and settings', size: [20, 20], grounds: ['band'],
          states: [K('rules', 'Rules', 'rulesMenu.svg'), K('rulesHover', 'Rules, hover', 'rulesMenuHover.svg'), K('settings', 'Settings', 'settings.svg', { size: [32, 32] })] },
        { id: 'skBadges', name: 'More badges', size: [20, 20], grounds: ['plateBlue'],
          states: [K('low', 'Low reputation', 'lowReputationBadge.svg'), K('dirty', 'Dirty meld', 'dirtyMeldBadge.svg'), K('high2', 'High reputation, numbered', 'highReputationBadge~2.svg'), K('exp', 'Experienced, yellow', 'experiencedBadge.svg')] },
        { id: 'skCount', name: 'A count chip', size: [32, 32], grounds: ['felt'], states: [K('rest', 'Rest', 'countChip.svg')] },
        { id: 'skError', name: 'A warning', size: [48, 48], grounds: ['white'], states: [K('rest', 'Rest', 'error.svg')] },
        { id: 'skRosettes', name: 'Place rosettes, five to eight', size: [56, 48], grounds: ['page'],
          states: [K('5', 'Fifth', '5.svg'), K('6', 'Sixth', '6.svg'), K('7', 'Seventh', '7.svg'), K('8', 'Eighth', '8.svg')] },
        { id: 'skBridge', name: 'Bridge banners', size: [296, 112], grounds: ['band'], wide: true,
          states: [K('grand', 'Grand slam', 'grandSlam.svg'), K('small', 'Small slam', 'smallSlam.svg'), K('rubber', 'Rubber won', 'rubberWon.svg')] },
        { id: 'skChecks', name: 'A yellow checkbox set', size: [24, 24], grounds: ['white'],
          states: [K('checked', 'Checked', 'checked.svg'), K('unchecked', 'Unchecked', 'unchecked.svg'), K('checkedOff', 'Checked, off', 'checked-disabled.svg'), K('uncheckedOff', 'Unchecked, off', 'unchecked-disabled.svg')] },
        { id: 'skArrows', name: 'Small arrows', size: [13, 13], grounds: ['white'],
          states: [K('big', 'Big', 'arrowDownBig.svg', { size: [15, 15] }), K('green', 'Green', 'arrowDownGreen.svg'), K('orange', 'Orange', 'arrowDownOrange.svg')] },
      ] },
  ],
};
