#!/usr/bin/env python3
"""logo-places.html: every place the settled logo and its icons went, drawn as they sit there. Run after make.py
and after the bar renders in places/ (bar-desktop.png, bar-phone.png, bar-flagoff.png, made with the lab's bar
page at 2x). Copies the site's files into places/ so the page stands on its own, online too.

    python3 places.py
"""
import pathlib, shutil
from html import escape
from PIL import Image

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent
P = HERE / 'places'
WOCG = pathlib.Path('/Users/holgersindbaek/CloudDrive/HolgerSindbaek/WorldOfCardGames/Programming/wocg/worldofcardgames')

FILES = [
    # (repo path, where it is used)
    ('static/images/logo.svg', 'The top menu: menu_bar.dust draws it 125x32 at flag-off; under the redesign 36px tall (27 on a phone), lifted 7%. Preloaded by head_open_ads.dust.'),
    ('static/images/logo.png', 'The eight account emails (node-user/emails/*.dust, a 180x46 box) through logoURL in node-user, node-payments and node-periodic.'),
    ('static/images/logoIcon.png', 'The maintenance page (down/index.html) at 160x160.'),
    ('web/public/favicon.ico', 'The browser tab and bookmarks, 16 24 32 48 64; also the desktop notification icon (Table.js).'),
    ('web/public/favicon.svg', 'The browser tab in Chrome, Firefox and Edge, which prefer the SVG (both head templates).'),
    ('web/public/favicons/favicon-16x16.png', 'The tab, linked at 16 (both head templates).'),
    ('web/public/favicons/favicon-32x32.png', 'The tab and the taskbar, linked at 32.'),
    ('web/public/favicons/favicon-96x96.png', 'Linked at 96.'),
    ('web/public/favicons/favicon-128.png', 'Linked at 128.'),
    ('web/public/favicons/favicon-196x196.png', 'Linked at 196: Android home screens.'),
    ('web/public/favicons/apple-touch-icon-57x57.png', 'iOS home screen, old sizes 57 60 72 76 114 120 144 152 (precomposed), on the band paper.'),
    ('web/public/favicons/apple-touch-icon-180x180.png', 'iOS home screen, the 180 iPhones ask for today; new, linked in both head templates.'),
    ('web/public/favicons/mstile-70x70.png', 'Windows start tiles 70 144 150 310x150 310x310, transparent on the tile colour #327333.'),
    ('web/public/worldofcardgames.jpg', 'The share image (og:image) for pages without their own, 1200x630.'),
]
COPY = ['static/images/logo.svg', 'static/images/logo.png', 'static/images/logoIcon.png', 'web/public/favicon.ico', 'web/public/favicon.svg',
        'web/public/favicons/favicon-16x16.png', 'web/public/favicons/favicon-32x32.png', 'web/public/favicons/favicon-96x96.png',
        'web/public/favicons/apple-touch-icon-180x180.png', 'web/public/favicons/apple-touch-icon-57x57.png', 'web/public/favicons/mstile-150x150.png',
        'web/public/favicons/mstile-310x150.png', 'web/public/worldofcardgames.jpg']

def main():
    P.mkdir(exist_ok=True)
    for rel in COPY:
        shutil.copy(WOCG / rel, P / pathlib.Path(rel).name)
    def size(rel):
        p = WOCG / rel
        if p.suffix == '.svg':
            return '%d KB' % (p.stat().st_size // 1024)
        im = Image.open(p)
        return '%dx%d' % im.size + (' (%s)' % ', '.join('%d' % s[0] for s in sorted(im.ico.sizes())) if p.suffix == '.ico' else '')
    rows = ''.join('<tr><td><code>%s</code></td><td>%s</td><td>%s</td></tr>' % (escape(rel), size(rel), escape(where)) for rel, where in FILES)
    html = PAGE % dict(rows=rows)
    (ROOT / 'logo-places.html').write_text(html)
    print('wrote logo-places.html')

PAGE = r'''<!DOCTYPE html>
<html lang="en">
<head>
<!-- Generated by logo-final/places.py. Edit places.py, then run it. -->
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>The settled logo: where it went &middot; lab</title>
<link rel="stylesheet" href="guide-fonts.css">
<style>
  :root { --paper: #f9f6f2; --band: #f4eee5; --ink: #141414; --label: #4e4d4c; --quiet: #67635c; --line: #d2cfca; }
  html, body { margin: 0; }
  body { background: var(--paper); color: var(--ink); font: 16px/24px "BuloRounded", "Verdana", sans-serif; -webkit-font-smoothing: antialiased; }
  .lp-head { padding: 18px 28px 12px; box-shadow: 0 1px 0 var(--line); }
  .lp-head h1 { margin: 0; font: 500 26px/32px "GLCA", Georgia, serif; }
  .lp-head p { margin: 6px 0 0; color: var(--label); font-size: 14px; line-height: 20px; max-width: 900px; }
  .lp-page { padding: 8px 28px 96px; max-width: 1400px; }
  .lp-page h2 { font: 500 22px/28px "GLCA", Georgia, serif; margin: 34px 0 4px; }
  .lp-desc { color: var(--label); font-size: 14px; line-height: 20px; max-width: 900px; margin: 0 0 12px; }
  .lp-shot { display: block; border-radius: 10px; box-shadow: inset 0 0 0 1px var(--line); max-width: 100%%; height: auto; }
  .lp-row { display: flex; flex-wrap: wrap; gap: 14px; align-items: flex-start; }
  .lp-card { background: #fff; border-radius: 12px; box-shadow: inset 0 0 0 1px var(--line); padding: 12px; }
  .lp-card span { display: block; font-size: 12px; line-height: 16px; color: var(--quiet); margin-top: 6px; }
  .tab { display: inline-flex; align-items: center; gap: 8px; height: 34px; padding: 0 14px 0 12px; background: #fff; border-radius: 10px 10px 0 0; box-shadow: inset 0 0 0 1px #cfcfcf; font: 13px/16px -apple-system, "Helvetica Neue", Arial, sans-serif; color: #202124; }
  .tabbar { background: #dee1e6; padding: 8px 8px 0; border-radius: 10px 10px 0 0; display: inline-block; }
  .tab img { width: 16px; height: 16px; }
  .home { display: inline-flex; flex-direction: column; align-items: center; gap: 6px; padding: 22px 26px; background: #2a2f3a; border-radius: 16px; color: #fff; font: 12px/14px -apple-system, "Helvetica Neue", Arial, sans-serif; }
  .home img { width: 60px; height: 60px; border-radius: 22%%; box-shadow: 0 2px 6px rgba(0, 0, 0, .35); }
  .tile { display: inline-block; padding: 0; background: #327333; }
  .tile img { display: block; width: 150px; height: 150px; }
  .tile.wide img { width: 310px; height: 150px; }
  .mail { width: 360px; background: #fff; border-radius: 8px; box-shadow: inset 0 0 0 1px var(--line); padding: 26px 0 18px; text-align: center; }
  .mail img { width: 180px; height: 46px; display: inline-block; }
  .mail p { margin: 14px 24px 0; font: 14px/20px Arial, sans-serif; color: #555; text-align: left; }
  .down { width: 360px; background: #f4eee5; border-radius: 8px; box-shadow: inset 0 0 0 1px var(--line); padding: 26px 0; text-align: center; font: 15px/22px Arial, sans-serif; color: #333; }
  .down img { width: 160px; height: 160px; display: block; margin: 0 auto 8px; }
  .big img { height: 64px; width: auto; display: block; }
  .zoom { image-rendering: pixelated; }
  table { border-collapse: collapse; font-size: 14px; line-height: 20px; margin-top: 8px; }
  th, td { text-align: left; vertical-align: top; padding: 6px 12px 6px 0; border-bottom: 1px solid var(--line); }
  th { color: var(--label); font-weight: 700; }
  code { font: 13px/18px Menlo, monospace; }
</style>
</head>
<body>
<header class="lp-head">
  <h1>The settled logo: where it went</h1>
  <p>Holger, 30 Sep: the fan of four aces of hearts with World of over Card Games, exported as logo, logo_icon and favicon. Every place on the site that draws a logo or an icon, with the new file in it, as it sits there. The bar renders are the lab&rsquo;s copy of the real menubar through the site&rsquo;s own CSS (dev was down); the rest are the files themselves in a mock of their place.</p>
</header>
<main class="lp-page">
  <h2>1. The top menu, the redesign, on a desktop</h2>
  <p class="lp-desc"><code>static/images/logo.svg</code> through <code>menu_bar.dust</code>: 36px tall, lifted 7%% of its height so the ink&rsquo;s centre sits on the bar&rsquo;s middle (the words hang low in the fan). The fan is the export&rsquo;s own vector; the words are traced from the 3x PNG until an export carries them as outlines.</p>
  <img class="lp-shot" src="logo-final/places/bar-desktop.png" width="940" height="60" alt="">
  <h2>2. The top menu on a phone</h2>
  <p class="lp-desc">27px tall, the same lift.</p>
  <img class="lp-shot" src="logo-final/places/bar-phone.png" width="390" height="60" alt="">
  <h2>3. The top menu with the redesign flag off (the old look)</h2>
  <p class="lp-desc">Master&rsquo;s bar keeps the image at 125x32 and clips its logo box to 38px, so it shows the fan alone, as it showed the old fan.</p>
  <img class="lp-shot" src="logo-final/places/bar-flagoff.png" width="940" height="40" alt="">
  <h2>4. The browser tab</h2>
  <p class="lp-desc"><code>favicon.ico</code> (16, 24, 32, 48, 64), the new <code>favicon.svg</code> and <code>favicons/favicon-16x16, 32x32, 96x96, 128, 196x196.png</code>, all from the favicon export (the fan with the big heart grown). Chrome, Firefox and Edge take the SVG; Safari the PNGs or the ICO.</p>
  <div class="lp-row">
    <div class="lp-card"><div class="tabbar"><span class="tab"><img src="logo-final/places/favicon-16x16.png" alt="">World of Card Games</span></div><span>favicon-16x16.png in a tab</span></div>
    <div class="lp-card"><div class="tabbar"><span class="tab"><img src="logo-final/places/favicon.svg" alt="">World of Card Games</span></div><span>favicon.svg in a tab</span></div>
    <div class="lp-card"><img class="zoom" src="logo-final/places/favicon-16x16.png" width="64" height="64" alt=""><span>favicon-16x16.png at 4x</span></div>
    <div class="lp-card"><img class="zoom" src="logo-final/places/favicon-32x32.png" width="128" height="128" alt=""><span>favicon-32x32.png at 4x</span></div>
    <div class="lp-card"><img src="logo-final/places/favicon.ico" width="64" height="64" alt=""><span>favicon.ico at 64</span></div>
    <div class="lp-card"><img src="logo-final/places/favicon-96x96.png" width="96" height="96" alt=""><span>favicon-96x96.png</span></div>
  </div>
  <h2>5. A phone&rsquo;s home screen</h2>
  <p class="lp-desc"><code>favicons/apple-touch-icon-180x180.png</code> (new, linked in both head templates) and the old sizes 57 to 152: the fan on the band&rsquo;s paper, opaque, since iOS paints a clear icon black. iOS rounds the corners itself.</p>
  <div class="lp-row">
    <div class="lp-card"><div class="home"><img src="logo-final/places/apple-touch-icon-180x180.png" alt="">Card Games</div><span>apple-touch-icon-180x180.png on a home screen</span></div>
    <div class="lp-card"><img src="logo-final/places/apple-touch-icon-180x180.png" width="180" height="180" alt=""><span>the file itself</span></div>
    <div class="lp-card"><img src="logo-final/places/apple-touch-icon-57x57.png" width="57" height="57" alt=""><span>apple-touch-icon-57x57.png</span></div>
  </div>
  <h2>6. Windows start tiles</h2>
  <p class="lp-desc"><code>favicons/mstile-70x70, 144x144, 150x150, 310x150, 310x310.png</code>: the fan, transparent, on the tile colour the head templates name (<code>#327333</code>, unchanged).</p>
  <div class="lp-row">
    <div class="lp-card"><div class="tile"><img src="logo-final/places/mstile-150x150.png" alt=""></div><span>mstile-150x150.png on the tile colour</span></div>
    <div class="lp-card"><div class="tile wide"><img src="logo-final/places/mstile-310x150.png" alt=""></div><span>mstile-310x150.png</span></div>
  </div>
  <h2>7. The account emails</h2>
  <p class="lp-desc"><code>static/images/logo.png</code> (374x96, the whole logo at the old file&rsquo;s height) in the eight emails of <code>node-user/emails/</code> (verify, forgot password, email changed, subscription started and cancelled, banned, ban lifted, change email), whose logo box went from 180x42 to 180x46 for the new aspect.</p>
  <div class="lp-row">
    <div class="lp-card"><div class="mail"><img src="logo-final/places/logo.png" alt=""><p>Hi Ann,</p><p>Welcome to World of Card Games. Press the button below to verify your email address.</p></div><span>logo.png in the email&rsquo;s box</span></div>
    <div class="lp-card big"><img src="logo-final/places/logo.png" alt=""><span>the file at 64px tall</span></div>
  </div>
  <h2>8. The maintenance page</h2>
  <p class="lp-desc"><code>static/images/logoIcon.png</code> (1280 square, the fan) at 160x160 in <code>down/index.html</code>.</p>
  <div class="lp-row"><div class="lp-card"><div class="down"><img src="logo-final/places/logoIcon.png" alt="">We&rsquo;ll be right back.</div><span>logoIcon.png on the maintenance page</span></div></div>
  <h2>9. The share image</h2>
  <p class="lp-desc"><code>web/public/worldofcardgames.jpg</code>, the og:image for pages without their own (a game page uses its screenshot): the logo on the page paper at 1200x630. The old file was an illustrated green card; it is in git.</p>
  <img class="lp-shot" src="logo-final/places/worldofcardgames.jpg" width="600" height="315" alt="">
  <h2>10. Every file, and where it is used</h2>
  <table><tr><th>File (in worldofcardgames/)</th><th>Size</th><th>Used by</th></tr>%(rows)s</table>
  <p class="lp-desc" style="margin-top: 16px">Not touched: the game apps&rsquo; own icons (Khang&rsquo;s per game), the per-game share screenshots, and the social icons in web/public (facebook-48, twitter-48, youtube-48).</p>
</main>
</body>
</html>
'''

if __name__ == '__main__':
    main()
